import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer {
	public static void main(String[] args) throws Exception {
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		// -Use the key to decrypt the incoming message from socket s.
		// -Print out the decrypt String to see if it matches the orignal message.
		ObjectInputStream inputStream = new ObjectInputStream(s.getInputStream());
		Key key = (Key) inputStream.readObject();

		// deciphering process
		Cipher desCipher = Cipher.getInstance("DES");
		desCipher.init(Cipher.DECRYPT_MODE, key);
		CipherInputStream tobeDecryptedStream = new CipherInputStream(s.getInputStream(), desCipher);
		int decryptedMessage = tobeDecryptedStream.read();

		// converting the result into a string
		StringBuilder dMessage = new StringBuilder();

		while (decryptedMessage != -1) {
			dMessage.append((char) decryptedMessage);
			decryptedMessage = tobeDecryptedStream.read();
		}

		System.out.println(dMessage.toString());

		inputStream.close();
		tobeDecryptedStream.close();
		server.close();
	}
}